// Sử dụng cú pháp proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/blockchain.proto

// Tên package của Protobuf

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          []byte                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`                 // ID của giao dịch chứa Output
	VoutIndex     int32                  `protobuf:"varint,2,opt,name=vout_index,json=voutIndex,proto3" json:"vout_index,omitempty"` // Vị trí (index) của Output
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                   // Chữ ký
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`  // Public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	mi := &file_proto_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *TxInput) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *TxInput) GetVoutIndex() int32 {
	if x != nil {
		return x.VoutIndex
	}
	return 0
}

func (x *TxInput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TxInput) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type TxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`                              // Số tiền
	PubKeyHash    []byte                 `protobuf:"bytes,2,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"` // Hash của Public Key (địa chỉ) khóa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	mi := &file_proto_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *TxOutput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           []*TxInput             `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`   // Danh sách các đầu vào
	Vout          []*TxOutput            `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"` // Danh sách các đầu ra
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetVin() []*TxInput {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Transaction) GetVout() []*TxOutput {
	if x != nil {
		return x.Vout
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevBlockHash []byte                 `protobuf:"bytes,2,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Nonce         int64                  `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type FindSpendableUTXOsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSpendableUTXOsRequest) Reset() {
	*x = FindSpendableUTXOsRequest{}
	mi := &file_proto_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSpendableUTXOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSpendableUTXOsRequest) ProtoMessage() {}

func (x *FindSpendableUTXOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSpendableUTXOsRequest.ProtoReflect.Descriptor instead.
func (*FindSpendableUTXOsRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *FindSpendableUTXOsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FindSpendableUTXOsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Một UTXO có thể tiêu
type SpendableUTXO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          []byte                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	VoutIndex     int32                  `protobuf:"varint,2,opt,name=vout_index,json=voutIndex,proto3" json:"vout_index,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PubKeyHash    []byte                 `protobuf:"bytes,4,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"` // Cần thiết để xác thực
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendableUTXO) Reset() {
	*x = SpendableUTXO{}
	mi := &file_proto_blockchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendableUTXO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendableUTXO) ProtoMessage() {}

func (x *SpendableUTXO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendableUTXO.ProtoReflect.Descriptor instead.
func (*SpendableUTXO) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *SpendableUTXO) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *SpendableUTXO) GetVoutIndex() int32 {
	if x != nil {
		return x.VoutIndex
	}
	return 0
}

func (x *SpendableUTXO) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpendableUTXO) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

type FindSpendableUTXOsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccumulatedAmount int64                  `protobuf:"varint,1,opt,name=accumulated_amount,json=accumulatedAmount,proto3" json:"accumulated_amount,omitempty"`
	Utxos             []*SpendableUTXO       `protobuf:"bytes,2,rep,name=utxos,proto3" json:"utxos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindSpendableUTXOsResponse) Reset() {
	*x = FindSpendableUTXOsResponse{}
	mi := &file_proto_blockchain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSpendableUTXOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSpendableUTXOsResponse) ProtoMessage() {}

func (x *FindSpendableUTXOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSpendableUTXOsResponse.ProtoReflect.Descriptor instead.
func (*FindSpendableUTXOsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{6}
}

func (x *FindSpendableUTXOsResponse) GetAccumulatedAmount() int64 {
	if x != nil {
		return x.AccumulatedAmount
	}
	return 0
}

func (x *FindSpendableUTXOsResponse) GetUtxos() []*SpendableUTXO {
	if x != nil {
		return x.Utxos
	}
	return nil
}

// Message xác nhận (Acknowledgment)
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_blockchain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request để lấy block
type GetBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash của block cuối cùng mà client có
	// (Nếu rỗng, nghĩa là xin toàn bộ)
	FromHash      []byte `protobuf:"bytes,1,opt,name=from_hash,json=fromHash,proto3" json:"from_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_proto_blockchain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlocksRequest) GetFromHash() []byte {
	if x != nil {
		return x.FromHash
	}
	return nil
}

// Request rỗng (dùng cho GetKnownNodes)
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_blockchain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{9}
}

// Response chứa danh sách các node
type KnownNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"` // ví dụ: "127.0.0.1:3000"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownNodesResponse) Reset() {
	*x = KnownNodesResponse{}
	mi := &file_proto_blockchain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownNodesResponse) ProtoMessage() {}

func (x *KnownNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownNodesResponse.ProtoReflect.Descriptor instead.
func (*KnownNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{10}
}

func (x *KnownNodesResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Địa chỉ ví cần kiểm tra
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_blockchain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{11}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"` // Số dư trả về
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_blockchain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blockchain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_blockchain_proto_rawDescGZIP(), []int{12}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_proto_blockchain_proto protoreflect.FileDescriptor

const file_proto_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x16proto/blockchain.proto\x12\x05proto\"z\n" +
	"\aTxInput\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\x12\x1d\n" +
	"\n" +
	"vout_index\x18\x02 \x01(\x05R\tvoutIndex\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"B\n" +
	"\bTxOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12 \n" +
	"\fpub_key_hash\x18\x02 \x01(\fR\n" +
	"pubKeyHash\"d\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12 \n" +
	"\x03vin\x18\x02 \x03(\v2\x0e.proto.TxInputR\x03vin\x12#\n" +
	"\x04vout\x18\x03 \x03(\v2\x0f.proto.TxOutputR\x04vout\"\xaf\x01\n" +
	"\x05Block\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0fprev_block_hash\x18\x02 \x01(\fR\rprevBlockHash\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x126\n" +
	"\ftransactions\x18\x04 \x03(\v2\x12.proto.TransactionR\ftransactions\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x03R\x05nonce\"M\n" +
	"\x19FindSpendableUTXOsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"}\n" +
	"\rSpendableUTXO\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\x12\x1d\n" +
	"\n" +
	"vout_index\x18\x02 \x01(\x05R\tvoutIndex\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12 \n" +
	"\fpub_key_hash\x18\x04 \x01(\fR\n" +
	"pubKeyHash\"w\n" +
	"\x1aFindSpendableUTXOsResponse\x12-\n" +
	"\x12accumulated_amount\x18\x01 \x01(\x03R\x11accumulatedAmount\x12*\n" +
	"\x05utxos\x18\x02 \x03(\v2\x14.proto.SpendableUTXOR\x05utxos\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetBlocksRequest\x12\x1b\n" +
	"\tfrom_hash\x18\x01 \x01(\fR\bfromHash\"\x0e\n" +
	"\fEmptyRequest\"2\n" +
	"\x12KnownNodesResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance2\x80\x03\n" +
	"\vNodeService\x121\n" +
	"\x0fSendTransaction\x12\x12.proto.Transaction\x1a\n" +
	".proto.Ack\x12)\n" +
	"\rAnnounceBlock\x12\f.proto.Block\x1a\n" +
	".proto.Ack\x124\n" +
	"\tGetBlocks\x12\x17.proto.GetBlocksRequest\x1a\f.proto.Block0\x01\x12?\n" +
	"\rGetKnownNodes\x12\x13.proto.EmptyRequest\x1a\x19.proto.KnownNodesResponse\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.proto.GetBalanceRequest\x1a\x19.proto.GetBalanceResponse\x12Y\n" +
	"\x12FindSpendableUTXOs\x12 .proto.FindSpendableUTXOsRequest\x1a!.proto.FindSpendableUTXOsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_blockchain_proto_rawDescOnce sync.Once
	file_proto_blockchain_proto_rawDescData []byte
)

func file_proto_blockchain_proto_rawDescGZIP() []byte {
	file_proto_blockchain_proto_rawDescOnce.Do(func() {
		file_proto_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blockchain_proto_rawDesc), len(file_proto_blockchain_proto_rawDesc)))
	})
	return file_proto_blockchain_proto_rawDescData
}

var file_proto_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_blockchain_proto_goTypes = []any{
	(*TxInput)(nil),                    // 0: proto.TxInput
	(*TxOutput)(nil),                   // 1: proto.TxOutput
	(*Transaction)(nil),                // 2: proto.Transaction
	(*Block)(nil),                      // 3: proto.Block
	(*FindSpendableUTXOsRequest)(nil),  // 4: proto.FindSpendableUTXOsRequest
	(*SpendableUTXO)(nil),              // 5: proto.SpendableUTXO
	(*FindSpendableUTXOsResponse)(nil), // 6: proto.FindSpendableUTXOsResponse
	(*Ack)(nil),                        // 7: proto.Ack
	(*GetBlocksRequest)(nil),           // 8: proto.GetBlocksRequest
	(*EmptyRequest)(nil),               // 9: proto.EmptyRequest
	(*KnownNodesResponse)(nil),         // 10: proto.KnownNodesResponse
	(*GetBalanceRequest)(nil),          // 11: proto.GetBalanceRequest
	(*GetBalanceResponse)(nil),         // 12: proto.GetBalanceResponse
}
var file_proto_blockchain_proto_depIdxs = []int32{
	0,  // 0: proto.Transaction.vin:type_name -> proto.TxInput
	1,  // 1: proto.Transaction.vout:type_name -> proto.TxOutput
	2,  // 2: proto.Block.transactions:type_name -> proto.Transaction
	5,  // 3: proto.FindSpendableUTXOsResponse.utxos:type_name -> proto.SpendableUTXO
	2,  // 4: proto.NodeService.SendTransaction:input_type -> proto.Transaction
	3,  // 5: proto.NodeService.AnnounceBlock:input_type -> proto.Block
	8,  // 6: proto.NodeService.GetBlocks:input_type -> proto.GetBlocksRequest
	9,  // 7: proto.NodeService.GetKnownNodes:input_type -> proto.EmptyRequest
	11, // 8: proto.NodeService.GetBalance:input_type -> proto.GetBalanceRequest
	4,  // 9: proto.NodeService.FindSpendableUTXOs:input_type -> proto.FindSpendableUTXOsRequest
	7,  // 10: proto.NodeService.SendTransaction:output_type -> proto.Ack
	7,  // 11: proto.NodeService.AnnounceBlock:output_type -> proto.Ack
	3,  // 12: proto.NodeService.GetBlocks:output_type -> proto.Block
	10, // 13: proto.NodeService.GetKnownNodes:output_type -> proto.KnownNodesResponse
	12, // 14: proto.NodeService.GetBalance:output_type -> proto.GetBalanceResponse
	6,  // 15: proto.NodeService.FindSpendableUTXOs:output_type -> proto.FindSpendableUTXOsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_blockchain_proto_init() }
func file_proto_blockchain_proto_init() {
	if File_proto_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blockchain_proto_rawDesc), len(file_proto_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blockchain_proto_goTypes,
		DependencyIndexes: file_proto_blockchain_proto_depIdxs,
		MessageInfos:      file_proto_blockchain_proto_msgTypes,
	}.Build()
	File_proto_blockchain_proto = out.File
	file_proto_blockchain_proto_goTypes = nil
	file_proto_blockchain_proto_depIdxs = nil
}
