// Sử dụng cú pháp proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/public.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_public_proto protoreflect.FileDescriptor

const file_proto_public_proto_rawDesc = "" +
	"\n" +
	"\x12proto/public.proto\x12\x05proto\x1a\x16proto/blockchain.proto2\xb7\x02\n" +
	"\rPublicService\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.proto.GetBalanceRequest\x1a\x19.proto.GetBalanceResponse\x12S\n" +
	"\x10GetContractState\x12\x1e.proto.GetContractStateRequest\x1a\x1f.proto.GetContractStateResponse\x123\n" +
	"\x11SubmitTransaction\x12\x12.proto.Transaction\x1a\n" +
	".proto.Ack\x12Y\n" +
	"\x12FindSpendableUTXOs\x12 .proto.FindSpendableUTXOsRequest\x1a!.proto.FindSpendableUTXOsResponseB\tZ\a./protob\x06proto3"

var file_proto_public_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),          // 0: proto.GetBalanceRequest
	(*GetContractStateRequest)(nil),    // 1: proto.GetContractStateRequest
	(*Transaction)(nil),                // 2: proto.Transaction
	(*FindSpendableUTXOsRequest)(nil),  // 3: proto.FindSpendableUTXOsRequest
	(*GetBalanceResponse)(nil),         // 4: proto.GetBalanceResponse
	(*GetContractStateResponse)(nil),   // 5: proto.GetContractStateResponse
	(*Ack)(nil),                        // 6: proto.Ack
	(*FindSpendableUTXOsResponse)(nil), // 7: proto.FindSpendableUTXOsResponse
}
var file_proto_public_proto_depIdxs = []int32{
	0, // 0: proto.PublicService.GetBalance:input_type -> proto.GetBalanceRequest
	1, // 1: proto.PublicService.GetContractState:input_type -> proto.GetContractStateRequest
	2, // 2: proto.PublicService.SubmitTransaction:input_type -> proto.Transaction
	3, // 3: proto.PublicService.FindSpendableUTXOs:input_type -> proto.FindSpendableUTXOsRequest
	4, // 4: proto.PublicService.GetBalance:output_type -> proto.GetBalanceResponse
	5, // 5: proto.PublicService.GetContractState:output_type -> proto.GetContractStateResponse
	6, // 6: proto.PublicService.SubmitTransaction:output_type -> proto.Ack
	7, // 7: proto.PublicService.FindSpendableUTXOs:output_type -> proto.FindSpendableUTXOsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_public_proto_init() }
func file_proto_public_proto_init() {
	if File_proto_public_proto != nil {
		return
	}
	file_proto_blockchain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_public_proto_rawDesc), len(file_proto_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_public_proto_goTypes,
		DependencyIndexes: file_proto_public_proto_depIdxs,
	}.Build()
	File_proto_public_proto = out.File
	file_proto_public_proto_goTypes = nil
	file_proto_public_proto_depIdxs = nil
}
